// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package telkomsigma.itbroadband.model.security;

import org.springframework.beans.factory.annotation.Configurable;
import telkomsigma.itbroadband.model.security.Principal;

privileged aspect Principal_Roo_Configurable {
    
    declare @type: Principal: @Configurable;
    
}
